### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by chips556** [zenzjtech/Ad-Finder-for-News-Feed#1]
Hi Zen, it is not working for me, it is refreshing non stop with 0 ads found

1) I have no extensions on except Ad Finder for News Feed
2) My facebook language is English (US)
3) My chrome version is 83.0.4103.61

**Comment by zenzjtech** [comment]
Hello, thank for your report.
Are you using version from Chrome store or from Github?
Could you also plz capture the UI/UX of your feed, as FB just update its UI/UX.

**Comment by chips556** [comment]
![image](https://user-images.githubusercontent.com/63504363/82689044-7295dd00-9c8c-11ea-929a-56e53d2d34ec.png)

I have tried the classic facebook UI, that one didn't work at all

I'm using the Chrome extension

**Comment by zenzjtech** [comment]
Yep.
Have you tried new FB UI yet? What is the result?

**Comment by chips556** [comment]
Hi Zen, I have tried both UIs, the classic UI does not work at all, the new UI keeps refreshing non stop, skipping past sponsored posts

**Comment by zenzjtech** [comment]
Hi Chips556,

My PC has been broken for a while, just too focus on fixing it. Sorry for inactivity.

If you are still interest, please try this version, which handles classic UI.

This version is currently in pending Review state, it might take several day for it to be available on webstore.

Thank you!

[AdFinder.zip](https://github.com/zenzjtech/Ad-Finder-for-News-Feed/files/4700766/AdFinder.zip)
